### PR TITLE
Fix blinking on Concept route for logged in users

### LINKED ISSUE #2607: Statically rendered user pages + concept pages
We've been pre-rendering track pages and challenge pages by enumerating over all available tracks and challenges. We now need to find a way to statically generate user pages (there are 1000s of these), and concept pages (we'll have 100s of these in the near future). 

Vercel's [Prerender functions](https://vercel.com/docs/build-output-api/v3/primitives#prerender-functions) API is supposed to allow for generating these on demand and caching. Let's implement this and also see if we can expose this as a generic ember plugin that others can use.

### PR DESCRIPTION
**Pull request by VasylMarchuk**
Closes #2607 

### Brief

This fixes the blinking on the Concept page caused by a blocking `findAll` in the route's model hook, when trying to fetch the Concept Engagement for logged in users.

### Details

- Add a `700ms` delay before scrolling down to the congratulations icon after completing a Concept
   - Added a `delay` argument to `app/modifiers/scroll-into-view`, by default `0`
- Better handling of `@latestConceptEngagement` argument in `app/components/concept`
- Move `latestConceptEngagement` from `ConceptRouteModel` into `ConceptController`, so that it can be `@tracked`
  - move setting up `latestConceptEngagement` from the route's `model` hook into `setupController` hook
- Better logic for finding the concept in the Concept route model hook
  - it tries to find the concept in the store cache (where it could be inserted from Shoebox)
  - and if it can't find the concept — it tries fetching it from the backend with `reload: true`
  - and only then it redirects to `404` if concept is not found
  - this fixes both the blinking, and visiting `/concepts/:slug` route from other `link-to` helpers
- Better logic for finding concept engagement model
  - it will return an existing engagement if one is cached in the store
  - it will create and return a new engagement otherwise
  - it will also schedule re-fetching of the engagement in the background and update the controller's `latestConceptEngagement` accordingly afterwards
- Fix the `visit` helper in `ConceptPage` page object
- Remove `visitConcept` helper from `ConceptsPage` page object

### Checklist

- [x] I've thoroughly self-reviewed my changes
- [x] I've added tests for my changes, unless they affect admin-only areas (or are otherwise not worth testing)
- [x] I've verified any visual changes using Percy (add a commit with `[percy]` in the message to trigger)

## Summary by CodeRabbit

- **New Features**
  - Introduced smoother scrolling on concept pages with a brief delay, resulting in a more fluid transition when new content is revealed.
  - Updated the URL structure for accessing concept pages, providing a more intuitive and consistent navigation experience.

- **Refactor**
  - Enhanced the management of user engagement data to ensure that progress tracking remains accurate and responsive during interactions.
  - Streamlined the logic for determining the current block group index, improving performance and clarity.
  - Improved the structure of acceptance tests for visiting concept pages, consolidating functionality for better maintainability.
  - Updated property bindings in templates for better data retrieval and usage.

### CODE REVIEW

File: app/routes/concept.ts [hunk 1]
```diff
@@ -10,13 +10,31 @@ import type MetaDataService from 'codecrafters-frontend/services/meta-data';
...
+import { tracked } from '@glimmer/tracking';
 
-export type ConceptRouteModel = {
+export class ConceptRouteModel {
   allConcepts: ConceptModel[];
   concept: ConceptModel;
   conceptGroup: ConceptGroupModel;
-  latestConceptEngagement: ConceptEngagementModel;
-};
+  @tracked latestConceptEngagement: ConceptEngagementModel;
```
Comment (rohitpaulk) [inline app/routes/concept.ts:19]: This is pretty non-standard - can we move the tracked property to be in the controller instead somehow?

**Review by rohitpaulk — CHANGES_REQUESTED** [review]
Added note re: how using a class for the route model is very non-standard

File: app/components/concept/index.hbs [hunk 2]
```diff
@@ -1,4 +1,9 @@
-<div {{did-insert this.handleDidInsertContainer}} {{will-destroy this.handleWillDestroyContainer}} ...attributes>
+<div
+  {{did-insert this.handleDidInsertContainer}}
+  {{did-update this.recalculateLastRevealedBlockGroupIndex @latestConceptEngagement}}
```
Comment (rohitpaulk) [inline app/components/concept/index.hbs:3]: @VasylMarchuk shouldn't this just work by default? We're using `latestConceptEngagement.currentProgressPercentage` inside a function, as long as that is tracked, the value should update automatically no?

File: app/routes/concept.ts (hunk 1 above)
Comment (VasylMarchuk) [reply app/routes/concept.ts:19]: Yes, I tried that initially, it needs to be a controller property, and it needs to be set up using the `setupController` hook, I can do that, it just seemed a bit messier, more code than just changing `type` -> `class`

Comment (VasylMarchuk) [reply app/routes/concept.ts]: I have reverted `ConceptRouteModel` back to being a `type`, and moved `latestConceptEngagement` property from the model into the `ConceptController`, where it is naturally `@tracked`.

I've also moved the logic of assigning `latestConceptEngagement` from the `model` hook into the `setupController` hook in the route.

**Review by rohitpaulk — APPROVED** [review]
