### PR TITLE
Fix language icons overflowing from course cards on the Profile page

### LINKED ISSUE #1768: Card items overflow out of cards
## Steps
1. Visit someone's profile (https://app.codecrafters.io/users/rohitpaulk)
2. Look into the challenges section
3. Some icons are overflowing out of their card (when a challenge has been solved with multiple languages)

(firefox)
firerfox

(chromium)
chrome

## Proposed solution
Make sure the icons don't overflow

### PR DESCRIPTION
**Pull request by VasylMarchuk**
Closes #1768 

### Brief

This fixes language icons overflowing from course cards on the Profile page

### Refactoring & preparation details

- [Refactored & simplified](https://github.com/codecrafters-io/frontend/pull/3414/changes/26eeb5112c31e2afd10e10b8d6f0d1a87d1c9048) `CourseProgressList.courseParticipationGroups` getter
- Converted `UserPage::CourseProgressListItem` component to TypeScript
- Converted `UserPage::CourseProgressListItem::ProgressBar` component to TypeScript
- Added `@types/array-to-sentence` package to the project

### Real Details

- Sorted `courseParticipations` on Profile page by `isCompleted` & `lastSubmissionAt`
- Limited the number of displayed `courseParticipations` to **5**

### Screenshot

Знімок екрана 2025-12-30 о 19 38 02

### Checklist

- [x] I've thoroughly self-reviewed my changes
- [x] I've added tests for my changes, unless they affect admin-only areas (or are otherwise not worth testing)
- [x] I've verified any visual changes using Percy (add a commit with `[percy]` in the message to trigger)

### CODE REVIEW

File: app/components/user-page/course-progress-list-item/index.ts [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+  get completedCourseParticipations() {
+    return this.args.courseParticipations.filter((item) => item.isCompleted);
+  }
+
+  get completedStagesCount() {
+    return Math.max(...this.args.courseParticipations.map((item) => item.completedStageSlugs).map((stage_list) => stage_list.length));
+  }
+
+  get course() {
+    return this.args.courseParticipations[0]?.course;
```
Comment (rohitpaulk) [inline app/components/user-page/course-progress-list-item/index.ts]:
```suggestion
    return this.args.courseParticipations[0]!.course;
```

We know that this won't be instantiated without at least one course participation in the group
